name: matric configuration

on:
    push:
    workflow_dispatch: 
    

jobs:
  deploy: 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [hello-world]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo docker details
        run: docker info

      - name: Run images on ${{ matrix.os }}
        run: docker run ${{ matrix.images}}

  